### ISSUE TITLE
Apps inheriting from Kivy_reloader.app don't have an accessible nursery

### ISSUE THREAD

**Issue by Diakon5** [kivy-school/kivy-reloader#53]
[ERROR  ] [Reloader    ] Error when building app
Traceback (most recent call last):
  File "/mnt/data/Github/AndroidKivyApp/.venv/lib/python3.11/site-packages/kivy_reloader/app.py", line 268, in rebuild
    self.build_root_and_add_to_window()
  File "/mnt/data/Github/AndroidKivyApp/.venv/lib/python3.11/site-packages/kivy_reloader/app.py", line 159, in build_root_and_add_to_window
    self.root = self.build()
                ^^^^^^^^^^^^
  File "/mnt/data/Github/AndroidKivyApp/mobileApp/budgetAssistantApp.py", line 44, in build
    Clock.schedule_once(partial(self.nursery.start_soon,self.db_init))
                                ^^^^^^^^^^^^
AttributeError: 'MainApp' object has no attribute 'nursery'

Trying to schedule something to run just before the build function, I simply cannot..

Out of sheer desperation, I have implemented my own run_async that's identical to the one defined in Kivy_reloader. When I subclass kivy_reloader.app, I get the above error. When I subclass the kivy.app, everything works

**Comment by Diakon5** [comment]
Commit 6c4f528bcfbe825192af6bda703e932af9391d14 addresses the issue. It was due to building the app in the "__init__" function instead of the "run" function
